name: Deploy to from Source Master
on:
  push:	
    branches:	
      - master
  schedule:
    - cron:  '0 1 * * *'


jobs:
  deploy:
    name: Checkout and Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm install
        npx @11ty/eleventy

    - name: Deploy to Master
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}