name: Rebuild and Deploy to gh-pages
on:
  push:	
    branches:	
      - master
  schedule:
    - cron:  '2 22 * * *'

jobs:
  deploy:
    name: Checkout and Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: npm install and build
      run: |
        npm ci --no-audit
        npm run build

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}